/**
 * Comment validation and rendering helpers.
 *
 * Comments are plain text end to end. No HTML is accepted, stored or rendered:
 * a body containing markup is stored verbatim and escaped at render time, so it
 * appears to the reader as the characters they typed.
 */
import { sanitizeField, sanitizeMultiline } from './sanitize';

export const NAME_MIN = 2;
export const NAME_MAX = 40;
export const BODY_MIN = 3;
export const BODY_MAX = 2_000;
export const EMAIL_MAX = 120;

/**
 * Deliberately permissive. This is a "did they obviously mistype it" check, not
 * an attempt to decide which addresses are real — strict patterns reject valid
 * addresses and the field is optional anyway.
 */
const EMAIL_PATTERN = /^[^\s@]+@[^\s@.]+\.[^\s@]+$/;

export type CommentStatus = 'pending' | 'approved' | 'rejected' | 'spam';

export interface CommentInput {
  articleSlug: string;
  displayName: string;
  body: string;
  parentId: number | null;
  /** Optional. Stored for a private reply; never published. */
  email: string | null;
}

export type ValidationResult =
  | { ok: true; value: CommentInput }
  | { ok: false; field: 'slug' | 'name' | 'body' | 'parent' | 'email'; message: string };

/** Article slugs are generated by the build; anything else is rejected. */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Validate a submitted comment.
 *
 * Messages are Turkish because they are shown to the visitor. Field names stay
 * English because they are part of the API contract.
 */
export function validateComment(raw: {
  slug?: unknown;
  name?: unknown;
  body?: unknown;
  parentId?: unknown;
  email?: unknown;
}): ValidationResult {
  const slug = sanitizeField(raw.slug, 120).toLowerCase();
  if (!slug || !SLUG_PATTERN.test(slug)) {
    return { ok: false, field: 'slug', message: 'Geçersiz içerik adresi.' };
  }

  const displayName = sanitizeField(raw.name, NAME_MAX);
  if (displayName.length < NAME_MIN) {
    return { ok: false, field: 'name', message: 'Lütfen en az 2 karakterlik bir isim yazın.' };
  }

  const body = sanitizeMultiline(raw.body, BODY_MAX);
  if (body.length < BODY_MIN) {
    return { ok: false, field: 'body', message: 'Yorumunuz çok kısa.' };
  }

  let parentId: number | null = null;
  if (raw.parentId !== undefined && raw.parentId !== null && raw.parentId !== '') {
    const parsed = Number.parseInt(String(raw.parentId), 10);
    if (!Number.isInteger(parsed) || parsed <= 0) {
      return { ok: false, field: 'parent', message: 'Geçersiz yanıt hedefi.' };
    }
    parentId = parsed;
  }

  // Optional. An empty value is stored as NULL rather than an empty string, so
  // "no address given" and "gave an empty address" are the same row state.
  let email: string | null = null;
  const rawEmail = sanitizeField(raw.email, EMAIL_MAX);
  if (rawEmail) {
    if (!EMAIL_PATTERN.test(rawEmail)) {
      return { ok: false, field: 'email', message: 'E-posta adresi geçerli görünmüyor.' };
    }
    email = rawEmail;
  }

  return { ok: true, value: { articleSlug: slug, displayName, body, parentId, email } };
}

export interface PublicComment {
  id: number;
  parentId: number | null;
  displayName: string;
  body: string;
  createdAt: string;
}

/**
 * Arrange approved comments into one level of threading.
 *
 * Deliberately one level. Deeper nesting is a different product; replies to
 * replies are attached to the same top-level parent.
 */
export function threadComments(rows: PublicComment[]): Array<
  PublicComment & {
    replies: PublicComment[];
  }
> {
  const roots = rows.filter((r) => r.parentId === null);
  const byParent = new Map<number, PublicComment[]>();
  const rootIds = new Set(roots.map((r) => r.id));

  for (const row of rows) {
    if (row.parentId === null) continue;
    // A reply whose parent is itself a reply is attached to the top-level root.
    const key = rootIds.has(row.parentId) ? row.parentId : findRoot(row, rows, rootIds);
    if (key === null) continue;
    const list = byParent.get(key) ?? [];
    list.push(row);
    byParent.set(key, list);
  }

  return roots.map((root) => ({ ...root, replies: byParent.get(root.id) ?? [] }));
}

function findRoot(row: PublicComment, rows: PublicComment[], rootIds: Set<number>): number | null {
  const seen = new Set<number>();
  let current: PublicComment | undefined = row;
  while (current && current.parentId !== null) {
    if (seen.has(current.id)) return null; // cycle guard
    seen.add(current.id);
    if (rootIds.has(current.parentId)) return current.parentId;
    const next: PublicComment | undefined = rows.find((r) => r.id === current!.parentId);
    current = next;
  }
  return null;
}
