/**
 * Sitemap.
 *
 * Written by hand rather than generated by an integration so the exclusions are
 * explicit and testable: /boss, /api, /collect and the search page must never
 * appear, and neither may draft or review content.
 */
import type { APIRoute } from 'astro';
import { CATEGORIES, SITE } from '../config/site';
import { READY_TOOLS } from '../config/tools';
import { articlePath, getAllArticles } from '../lib/content';

const STATIC_PATHS = [
  '/',
  '/rehberler/',
  '/efsane-mi-gercek-mi/',
  '/teknik/',
  '/araclar/',
  '/haberler/',
  '/konular/',
  '/hakkinda/',
  '/iletisim/',
  '/gizlilik/',
];

export const GET: APIRoute = async () => {
  const articles = (await getAllArticles()).filter((a) => a.data.status === 'published');

  const entries: Array<{ loc: string; lastmod?: string }> = [
    ...STATIC_PATHS.map((path) => ({ loc: new URL(path, SITE.url).href })),
    // Tool pages come from the shared registry, so a new tool cannot ship
    // without appearing here. `planned` tools have no URL and are excluded.
    ...READY_TOOLS.map((tool) => ({ loc: new URL(tool.href ?? '/araclar/', SITE.url).href })),
    ...CATEGORIES.map((category) => ({
      loc: new URL(`/konular/${category.id}/`, SITE.url).href,
    })),
    ...articles.map((entry) => ({
      loc: new URL(articlePath(entry), SITE.url).href,
      lastmod: (entry.data.updatedAt ?? entry.data.publishedAt).toISOString(),
    })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map(
    (entry) =>
      `  <url><loc>${entry.loc}</loc>${
        entry.lastmod ? `<lastmod>${entry.lastmod}</lastmod>` : ''
      }</url>`,
  )
  .join('\n')}
</urlset>`;

  return new Response(xml, {
    headers: { 'content-type': 'application/xml; charset=utf-8' },
  });
};
