#!/usr/bin/env python3
"""
Generate public/favicon.svg and the PNG icon fallbacks.

Run only when the mark changes:  python3 scripts/generate-icons.py

The letterforms come from scripts/brandmark.py, which holds the same JetBrains
Mono Bold outlines the header renders as live text. Nothing here is drawn by
hand — see the note at the top of that module for why.

The icons carry the REDUCED mark, TC/, because the full <TC/> is not legible in
a 16px browser tab. Everything else about it is unchanged: same face, same
colour roles, C red, slash neutral and no taller than the letters.
"""
import os
import sys

from PIL import Image, ImageDraw

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import brandmark as bm  # noqa: E402

BOX = 32.0  # design space, shared with the SVG viewBox
CORNER = 6.0
MARK_WIDTH = 26.5  # of 32 — leaves an even optical margin
EM = MARK_WIDTH / (len(bm.REDUCED) * bm.ADVANCE / bm.UPM)
ORIGIN_X = (BOX - MARK_WIDTH) / 2
BASELINE = (BOX + bm.cap_height(EM)) / 2

SIZES = [(180, "apple-touch-icon.png"), (192, "icon-192.png"), (512, "icon-512.png")]


def render(size: int) -> Image.Image:
    """Supersample then downsample — smooth edges without an SVG rasteriser."""
    ss = 8 if size <= 192 else 4
    s = size * ss
    k = s / BOX
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([0, 0, s - 1, s - 1], radius=CORNER * k, fill=bm.BG)
    bm.draw_mark(d, bm.REDUCED, ORIGIN_X, BASELINE, EM, scale=k)
    return img.resize((size, size), Image.LANCZOS)


def svg() -> str:
    by_char: dict[str, list[str]] = {}
    for char, _colour, contour in bm.mark_contours(bm.REDUCED, ORIGIN_X, BASELINE, EM):
        path = "M" + " L".join(f"{x:.2f} {y:.2f}" for x, y in contour) + " Z"
        by_char.setdefault(char, []).append(path)
    body = "\n".join(
        f'  <path d="{" ".join(by_char[c])}" fill="{bm.hex_of(bm.COLOURS[c])}"/>'
        for c in bm.REDUCED
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" aria-label="TurkCyber">
  <title>TurkCyber</title>
  <!--
    GENERATED by scripts/generate-icons.py — do not hand-edit.

    The same TC/ letterforms as the header mark (JetBrains Mono Bold), reduced
    from the full <TC/> because five glyphs are not legible in a 16px tab.
    T warm white, C Turkish red, slash neutral grey — never green.
  -->
  <rect width="32" height="32" rx="6" fill="{bm.hex_of(bm.BG)}"/>
{body}
</svg>
"""


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "public"
    with open(os.path.join(out, "favicon.svg"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(svg())
    print("wrote favicon.svg")
    for size, name in SIZES:
        render(size).save(os.path.join(out, name))
        print("wrote", name, size)
